language: en

pipeline: supervised_embeddings

policies:
  - name: EmbeddingPolicy
    max_history: 5
    epochs: 200
    batch_size: 50
    max_training_samples: 300
  - name: FallbackPolicy
  - name: MemoizationPolicy
  - name: MappingPolicy
