language: python
sudo: enabled
dist: xenial
cache:
  directories:
  - $HOME/.cache/pip
  - /tmp/cached/
python: '3.6'
env:
  # needed to fix issues with boto during testing:
  # https://github.com/travis-ci/travis-ci/issues/7940
  global:
  - BOTO_CONFIG=/dev/null
  - COVERALLS_PARALLEL=true

install:
  - sudo apt-get install graphviz graphviz-dev
  - python -m pip install -U pip
  - pip install git+https://github.com/tmbo/MITIE.git
  - pip install -r requirements-dev.txt
  - pip install --no-use-pep517 -e .
  - pip install coveralls==1.3.0
  - pip install https://github.com/explosion/spacy-models/releases/download/en_core_web_md-2.0.0/en_core_web_md-2.0.0.tar.gz --no-cache-dir > jnk
  - python -m spacy link en_core_web_md en
  - pip install https://github.com/explosion/spacy-models/releases/download/de_core_news_sm-2.0.0/de_core_news_sm-2.0.0.tar.gz --no-cache-dir > jnk
  - python -m spacy link de_core_news_sm de
  - if [[ ! -f /tmp/cached/total_word_feature_extractor.dat ]]; then
    travis_wait wget --quiet -P /tmp/cached/ https://s3-eu-west-1.amazonaws.com/mitie/total_word_feature_extractor.dat;
    fi
  - mv /tmp/cached/total_word_feature_extractor.dat data/total_word_feature_extractor.dat
  - pip list
before_script:
  - mkdir $HOME/tmp
  - export TMPDIR=$HOME/tmp
after_success:
  - coveralls
jobs:
  include:
  - stage: test
    name: "Black Formatting"
    python: 3.6
    script: pip install black; black --check .
  - stage: test
    name: "Test Codestyle"
    python: 3.6
    script:
      - py.test --codestyle -m codestyle
  - &test-core
    stage: test
    name: "Test Core 3.6"
    python: "3.6"
    script:
      - py.test tests/core --cov rasa -v --cov-append
  - <<: *test-core
    name: "Test Core 3.5"
    python: '3.5'
  - <<: *test-core
    name: "Test Core 3.7"
    python: '3.7'
  - &test-nlu-base
    stage: test
    name: "Test NLU 3.6"
    python: "3.6"
    script:
      - py.test tests/nlu/base --cov rasa -v --cov-append
  - <<: *test-nlu-base
    name: "Test NLU 3.5"
    python: '3.5'
  - <<: *test-nlu-base
    name: "Test NLU 3.7"
    python: '3.7'
  - &test-nlu-training
    stage: test
    name: "Test NLU training 3.6"
    python: "3.6"
    script:
      - py.test tests/nlu/training --cov rasa -v --cov-append
  - <<: *test-nlu-training
    name: "Test NLU training 3.5"
    python: '3.5'
  - <<: *test-nlu-training
    name: "Test NLU training 3.7"
    python: '3.7'
  - stage: integration
    name: "Test API specification"
    language: python
    install:
    - npm install -g swagger-cli
    script:
    - swagger-cli validate docs/core/_static/spec/server.yml
    - swagger-cli validate docs/core/_static/spec/action_server.yml
    after_success:
    - coveralls
  - stage: test
    if: branch =~ /(\d+\.\d+\.x)/ or branch = "master" # only new version PRs & PRs to master will test starter packs
    name: "NLU starter pack (NLU only)"
    python: 3.6
    script:
    - git clone -b latest https://github.com/RasaHQ/starter-pack-rasa-nlu.git
    - cd starter-pack-rasa-nlu
    - python -m pytest tests
  - stage: test
    name: "Test CLI"
    script:
    - timeout 2 time rasa --help
  - stage: test
    if: branch =~ /(\d+\.\d+\.x)/ or branch = "master" # only new version PRs & PRs to master will test starter packs
    name: "Stack starter pack"
    python: 3.6
    script:
    - git clone -b latest https://github.com/RasaHQ/starter-pack-rasa-stack.git
    - cd starter-pack-rasa-stack
    - python -m pytest tests
  - stage: integration
    name: "Test Docs Core"
    install:
    - pip install -r requirements-docs.txt
    - pip install -e .
    - pip list
    script:
      # be strict about warnings --> they will be treated as errors
    - cd docs/core
    - make SPHINXOPTS="-W --keep-going -A html_theme=rasabaster" html
  - stage: integration
    name: "Test Docs NLU"
    install:
    - pip install -r requirements-docs.txt
    - pip install -e .
    - pip list
    script:
      # be strict about warnings --> they will be treated as errors
    - cd docs/nlu
    - make SPHINXOPTS="-W --keep-going -A html_theme=rasabaster" html
  - stage: deploy
    name: "Deploy to PyPI"
    python: 3.6
    install: skip
    script: skip
    deploy:
      provider: pypi
      user: amn41
      # server: https://test.pypi.org/legacy/
      distributions: "sdist bdist_wheel"
      on:
        branch: master
        tags: true
      password:
        secure: "MeL1Ve97eBY+VbNWuQNuLzkPs0TPc+Zh8OfZkhw69ez5imsiWpvp0LrUOLVW3CcC0vNTANEBOVX/n1kHxfcqkf/cChNqAkZ6zTMmvR9zHDwQxXVGZ3jEQSQM+fHdQpjwtH7BwojyxaCIC/5iza7DFMcca/Q6Xr+atdTd0V8Q7Nc5jFHEQf3/4oIIm6YeCUiHcEu981LRdS04+jvuFUN0Ejy+KLukGVyIWyYDjjGjs880Mj4J1mgmCihvVkJ1ujB65rYBdTjls3JpP3eTk63+xH8aHilIuvqB8TDYih8ovE/Vv6YwLI+u2HoEHAtBD4Ez3r71Ju6JKJM7DhWb5aurN4M7K6DC8AvpUl+PsJbNP4ZeW2jXMH6lT6qXKVaSw7lhZ0XY3wunyVcAbArX4RS0B9pb1nHBYUBWZjxXtr8lhkpGFu7H43hw63Y19qb8z4+1cGnijgz1mqXSAssuc+3r0W0cSr+OsCjmOs7cwT6HMQvPEKxLohwBOS/I3EbuKQOYMjFN5BWP5JXbsG45awV9tquxEW8zxjMetR+AOcYoyrDeiR8sAnj1/F99DE0bL1KyW/G5VNu2Xi/c+0M3KvP3+F8XTCuUY/5zTvqh1Qz1jcdiwsiAhO4eBQzQnjeFlxdiVeue2kmD5qsh+VLKKuKLfyVoaV7b1kBlAtBDu7+hDpA="
