language: python
sudo: enabled
cache:
  directories:
  - $HOME/.cache/pip
  - /tmp/cached/
python:
  - '2.7'
  - '3.5'
  - '3.6'
env:
  # needed to fix issues with boto during testing:
  # https://github.com/travis-ci/travis-ci/issues/7940
  global:
  - BOTO_CONFIG=/dev/null
  # secret for FOSSA
  - secure: "g0c6z+CKVPiuGE3G3OGjzcKZJsdsA/j+zsTQ/xr1ie9gKNpKRA0KQAvsU/mow4NeMmt5YKnwKxFqWy0b3Oufm5WLTAWIVepT5FHA7YMVCMcpPIMsbtqe64FqJxhgL+sBJZku5i94PzCruXwbjk3Q5Uad95ZsIJLQLEkzIla6Fdcu5hdkfYVIGRGe0W2YxNVx+3fZimnOOvJmXD/nnZEBesq5fR09uA4v2PsBGuHOTkwuG60rU5bBPZ2PNiEZXt552kJ5yfdSszNd6uzgQNp10L0qXzt1fXeyf9uGAleDS1HrbcVcdWX0jwCwZF/FD40wUcyKGqOWWDs81mehsjhXymKBhy62QinCSFBmcJb/uRJpMWvvzOLaH94TgxFJCxogNKdqNN/jU3V8CuJ2ELp+RCiniO1u9Dd134j6dYWSWYO+R4WXYoIQYVlGZZqIZz+5b5eKsY+r6I1zPBfD+MowJx2HiLpSdgXh3tlhblOZwPKIuUQ++MeBY4JttJA4Sx5K+YIUzDvcx+7jyuYIjrV4D23n6i4dZZHpAqqtlf1iSbnEzO/rnAxZxy1UuEVmXNJSDOoKEzA7Mdd/Nh+M8wcJAb/KDS/TEvT27+TLRlrgOjgjU2q+4yXNomivi3rZJ1+EFUTgs7lgOGCM/LBpJgnyyiSYZoep0YDZHtA3DCnHKQI="

install: 
  - pip install git+https://github.com/tmbo/MITIE.git
  - pip install -r alt_requirements/requirements_dev.txt
  - pip install -e .
  - pip install https://github.com/explosion/spacy-models/releases/download/en_core_web_md-2.0.0/en_core_web_md-2.0.0.tar.gz --no-cache-dir > jnk
  - python -m spacy link en_core_web_md en
  - pip install https://github.com/explosion/spacy-models/releases/download/de_core_news_sm-2.0.0/de_core_news_sm-2.0.0.tar.gz --no-cache-dir > jnk
  - python -m spacy link de_core_news_sm de
  - if [[ ! -f /tmp/cached/total_word_feature_extractor.dat ]]; then wget --quiet -P /tmp/cached/ https://s3-eu-west-1.amazonaws.com/mitie/total_word_feature_extractor.dat;
    fi
  - mv /tmp/cached/total_word_feature_extractor.dat data/total_word_feature_extractor.dat
  - pip list
before_script:
  - mkdir $HOME/tmp
  - export TMPDIR=$HOME/tmp
script: 
  - py.test --pep8 -m pep8
  - py.test tests/base --cov rasa_nlu -v --cov-append
  - py.test tests/training --cov rasa_nlu -v --cov-append
after_success:
  - coveralls
jobs:
  include:
  - stage: test
    name: Check Dependency Licenses
    before_script:
    - "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | sudo bash"
    script:
    - pip freeze > requirements.txt
    - fossa init
    - fossa analyze
    - fossa test
  - stage: docs
    if: fork = false AND branch = "master" # forked repository will skip building docs, only master & PRs to it
    install:
    - RASABASTER=rasabaster-0.7.18.tar.gz
    - curl -sSL -o $RASABASTER "https://storage.googleapis.com/docs-theme/${RASABASTER}?q=$(date +%s%N)"
    - pip install $RASABASTER
    - pip install --no-cache-dir -r alt_requirements/requirements_docs.txt
    - pip install git+https://${GITHUB_TOKEN}:x-oauth-basic@github.com/RasaHQ/sphinxcontrib-versioning.git@version_list
    - pip install -e .
    - pip list
    script:
    - eval "$(ssh-agent -s)"; touch docs_key; chmod 0600 docs_key
    - openssl aes-256-cbc
      -K $encrypted_1708c37fe733_key
      -iv $encrypted_1708c37fe733_iv
      -in secrets.tar.enc
      -out secrets.tar
      -d
    - tar -xvf secrets.tar
    - ssh-add docs_key
    - git config --global user.email "builds@travis-ci.com"
    - git config --global user.name "Travis CI"
    - git remote set-url --push origin "git@github.com:$TRAVIS_REPO_SLUG"
    - export ${!TRAVIS*}
    - sphinx-versioning push docs newdocs . -- -b dirhtml  -A html_theme=rasabaster
  - stage: test
    if: ".x" in branch # only new NLU version builds test the starter packs
    name: "NLU starter pack"
    python: 3.6
    script:
    - git clone https://github.com/RasaHQ/starter-pack-rasa-nlu.git
    - cd starter-pack-rasa-nlu
    - python -m pytest tests/test_nlu.py
  - stage: test
    if: ".x" in branch # only new NLU version builds test the starter packs
    python: 3.6
    script:
    - git clone https://github.com/RasaHQ/starter-pack-rasa-stack.git
    - cd starter-pack-rasa-stack
    - python -m pytest tests/test_nlu.py
  - stage: trigger website rebuild
    if: fork = false AND branch = "master" AND type != "pull_request"
    script:
    - eval "$(ssh-agent -s)";
      touch nlu_docs_to_website_trigger_key;
      chmod 0600 nlu_docs_to_website_trigger_key
    - openssl aes-256-cbc
      -K $encrypted_1708c37fe733_key
      -iv $encrypted_1708c37fe733_iv
      -in secrets.tar.enc
      -out secrets.tar
      -d
    - tar xvf secrets.tar
    - ssh-add nlu_docs_to_website_trigger_key
    - git config --global user.email "builds@travis-ci.com"
    - git config --global user.name "Travis CI"
    - git clone -b master --single-branch git@github.com:RasaHQ/rasa-website.git
    - cd rasa-website
    - git commit --allow-empty -m "trigger nlu docs update"
    - git push origin master
  - stage: deploy
    python: 3.6
    install: skip
    script: skip
    deploy:
      provider: pypi
      user: amn41
      # server: https://test.pypi.org/legacy/
      distributions: "sdist bdist_wheel"
      on:
        branch: master
        tags: true
      password:
        secure: "MeL1Ve97eBY+VbNWuQNuLzkPs0TPc+Zh8OfZkhw69ez5imsiWpvp0LrUOLVW3CcC0vNTANEBOVX/n1kHxfcqkf/cChNqAkZ6zTMmvR9zHDwQxXVGZ3jEQSQM+fHdQpjwtH7BwojyxaCIC/5iza7DFMcca/Q6Xr+atdTd0V8Q7Nc5jFHEQf3/4oIIm6YeCUiHcEu981LRdS04+jvuFUN0Ejy+KLukGVyIWyYDjjGjs880Mj4J1mgmCihvVkJ1ujB65rYBdTjls3JpP3eTk63+xH8aHilIuvqB8TDYih8ovE/Vv6YwLI+u2HoEHAtBD4Ez3r71Ju6JKJM7DhWb5aurN4M7K6DC8AvpUl+PsJbNP4ZeW2jXMH6lT6qXKVaSw7lhZ0XY3wunyVcAbArX4RS0B9pb1nHBYUBWZjxXtr8lhkpGFu7H43hw63Y19qb8z4+1cGnijgz1mqXSAssuc+3r0W0cSr+OsCjmOs7cwT6HMQvPEKxLohwBOS/I3EbuKQOYMjFN5BWP5JXbsG45awV9tquxEW8zxjMetR+AOcYoyrDeiR8sAnj1/F99DE0bL1KyW/G5VNu2Xi/c+0M3KvP3+F8XTCuUY/5zTvqh1Qz1jcdiwsiAhO4eBQzQnjeFlxdiVeue2kmD5qsh+VLKKuKLfyVoaV7b1kBlAtBDu7+hDpA="
