language: python
sudo: required
cache:
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/build/amn41/rasa_core/data"
python:
- '2.7'
- '3.5'
- '3.6'
install:
- sudo apt-get update
- sudo apt-get install graphviz graphviz-dev
- pip install -r dev-requirements.txt
- pip install -e .
- pip install coveralls==1.3.0
- pip list
script:
- travis_wait py.test tests --cov rasa_core --pep8 -v
 #- cd docs && make doctest   # can't do yet - doctests need to be cleaned up first
after_success:
- openssl aes-256-cbc -K $encrypted_050c822e99ef_key -iv $encrypted_050c822e99ef_iv
  -in docs/key.enc -out docs/key -d
- coveralls
jobs:
  include:
  - stage: Test API specification
    language: python
    install:
    - npm install -g swagger-cli
    script:
    - swagger-cli validate docs/_static/spec/server.yml
    after_success:
    - coveralls
  - stage: docs
    if: fork = false AND branch = "master"
    install:
    - sudo apt-get update
    - pip install -r docs-requirements.txt
    - pip install -e .
    - pip list
    script:
    - eval "$(ssh-agent -s)"; touch docs/key; chmod 0600 docs/key
    - openssl aes-256-cbc
      -K $encrypted_050c822e99ef_key
      -iv $encrypted_050c822e99ef_iv
      -in docs/key.enc
      -out docs/key
      -d && ssh-add docs/key
    - git config --global user.email "builds@travis-ci.com"
    - git config --global user.name "Travis CI"
    - git remote set-url --push origin "git@github.com:$TRAVIS_REPO_SLUG"
    - export ${!TRAVIS*}
    - sphinx-versioning push docs newdocs . -- -b dirhtml -A html_theme=rasabaster
  - stage: deploy
    python: 3.6
    install: skip
    script: skip
    deploy:
      provider: pypi
      user: amn41
      distributions: "sdist bdist_wheel"
      on:
        branch: master
        tags: true
      password:
        secure: "GEYe86FJaEg5W1P5G2FsATRaCAus8CzIwEvMLQtO8Y1zYKpUggOGgLu91fj0Z6zR8/lw2ZoAvMmrlOOwi9MyuAA3I5u7wOeiJZGzLAyyWGAG5oOqWYUF+zVjNmUqmYn/32VWdsRbnGVhcQBdswf/BHyAdD/s0ZWfI590u9xeR58hjHgD4vXXa6ep5RFo0Umv1IVivPTbmi3Q3Pf4Pmf1Lq0zlZJJEwyoXYeXwGIoxT//PtkYnakUY6JNmC7/CF7+ixF1jLwovNS6jjpJXDJEn/475LS90SuKKD4xvQ/z6486Qtn1P1dx6Uuw2p1zLY73tS3lZc2wBFPXME7ri4xtLn1bcxey3s/6f4fbuW+W+yXc7uTjNo/PEk/WKG89I98NHcfRlIsggpNSwVudRh27h3dI2Fa0QSlpKfd7mgj8sZb+gVE8er2frrrYhBVE+SFuKh36DCO1FHuVfxcPCtYcFqut/PhSQ062RIgT5MjOE3baS6F2cNwrSM7kYKPIRgMEp5/9p/I1iyjC0xreqGgw9Rthaaog9EcfZeUW1Y2XmqyQt391kO/w8WhFCsfhnj6BlI5hLzo/cr1lhoFT0/v4iKYcpCeaz1WoEeEqZ2KN0ImKPOhStViBPwO1F40SOeIj+sigtSN/6Pxvw+q2gfkSH3iSczik5ZkOfeSXl3Bvpkc="
