language: en

pipeline:
  - name: "SpacyNLP"
  - name: "SpacyTokenizer"
  - name: "SpacyFeaturizer"
  - name: "LexicalSyntacticFeaturizer"
  - name: "DIETClassifier"
    epochs: 100
  - name: "EntitySynonymMapper"

policies:
  - name: "examples.restaurantbot.policy.RestaurantPolicy"
    batch_size: 100
    epochs: 100
    validation_split: 0.2
  - name: MemoizationPolicy
  - name: MappingPolicy
