language: "en"

pipeline:
- name: "SpacyNLP"
  model: "en"
- name: "SpacyTokenizer"
- name: "SpacyEntityExtractor"
- name: "DucklingHTTPExtractor"
  url: "http://duckling:8000"
  dimensions:
  - "NUMBER"
- name: "CRFEntityExtractor"
  BILOU_flag: true
  features:
    # features for word before token
    - ["low", "title", "upper", "pos", "pos2"]
    # features of token itself
    - ["bias", "low", "word3", "word2", "upper", "title", "digit", "pos", "pos2", "pattern"]
    # features for word after the token we want to tag
    - ["low", "title", "upper", "pos", "pos2"]
  max_iterations: 50
  L1_c: 1
  L2_c: 1e-3
- name: "SklearnIntentClassifier"
  C: [1, 2, 5, 10, 20, 100]
  kernel: "linear"