language: en

pipeline: supervised_embeddings

policies:
  - name: KerasPolicy
    epochs: 200
    batch_size: 50
    max_training_samples: 300
  - name: FallbackPolicy
    fallback_action_name: 'action_default_fallback'
  - name: MemoizationPolicy
    max_history: 5
  - name: FormPolicy
  - name: MappingPolicy
