recipe: default.v1
language: en
pipeline:
  - name: LLMCommandGenerator
    llm:
      model_name: gpt-4

policies:
  - name: rasa.core.policies.flow_policy.FlowPolicy
#  - name: EnterpriseSearchPolicy
#  - name: RulePolicy

assistant_id: 20230405-114328-tranquil-mustard
