language: en

pipeline:
  - name: "WhitespaceTokenizer"
  - name: "CountVectorsFeaturizer"
  - name: "DIETClassifier"
    entity_recognition: False
    epochs: 50
  - name: ResponseSelector
    epochs: 50

policies:
  - name: TEDPolicy
    max_history: 5
    epochs: 100
  - name: MemoizationPolicy
  - name: RulePolicy
