recipe: default.v1
assistant_id: mood_bot
language: en

pipeline:
  - name: "SpacyNLP"
    model: "en_core_web_md"
  - name: "SpacyTokenizer"
  - name: "SpacyFeaturizer"
  - name: "DIETClassifier"
    entity_recognition: False
    epochs: 1

policies:
  - name: TEDPolicy
    max_history: 5
    epochs: 1
  - name: MemoizationPolicy
  - name: RulePolicy
