name: Automatic PR Merger

on:
  push: {} # update PR when base branch is updated

jobs:
  # thats's all. single step is needed - if PR is mergeable according to
  # branch protection rules it will be merged automatically
  mergepal:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: rasahq/update-pr-branch@601ac3dadf708b14e7f0252d98230538235f99d9
        if: github.repository == 'RasaHQ/rasa'
        with:
          token: ${{ secrets.RASABOT_AUTOMERGE_GITHUB_TOKEN }}
          # required parameter by original action - 
          # check is already done through protected branches so not needed for us
          required_approval_count: 0
