name: Check if dependencies can be updated and create a pull request with updated ones.
on:
  schedule:
    # Run at 05:00 on Wednesday
    - cron:  '0 5 * * 3'

jobs:
  update_dependencies:
    runs-on: ubuntu-22.04
    name: Update dependencies
    steps:
      - uses: RasaHQ/dependabot-batch-updater@f049cbb0bbd3754bcb5ab154a79f00cd780fc633 # v1.0
        with:
          repo-token: ${{ secrets.RASABOT_GITHUB_TOKEN }}
          repository: RasaHQ/rasa
          directory: /
          package-manager: pip
          batch-size: 5
