# This is a installation test that we run daily. We attempt to install Rasa
# on Ubuntu, Mac and Windows and try to run `rasa init`. The goal here is to
# catch installation issues in an automated way.

name: Cron Test to Check Pip Installation

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          [ubuntu-22.04, ubuntu-18.04, macos-latest, windows-2019, windows-2022]
        python-version: [3.8, 3.9, '3.10']
      fail-fast: false

    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@57ded4d7d5e986d7296eab16560982c6dd7c923b
        with:
          python-version: ${{ matrix.python-version }}
      - name: Try to install Rasa.
        run: |
          python -m pip install rasa
      - name: Try to install Rasa[full].
        run: |
          python -m pip install rasa[full]
      - name: Try to run Rasa.
        run: |
          python -m rasa --version
          # Must create a folder first
          mkdir rasa-demo
          # Next we try to init. 
          python -m rasa init --init-dir rasa-demo --no-prompt
      - name: Notify slack on failure
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@3665186a8c1a022b28a1dbe0954e73aa9081ea9e
        with:
          channel_id: ${{ secrets.SLACK_ALERTS_CHANNEL_ID }}
          status: FAILED
          color: danger
